# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - confluent
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - confluent

networks:
  confluent:
    external: true
